import React from 'react';
import { SmeHelperContext } from '../types';

interface TermsOfServicePageProps {
  onSetHelperContext: (context: SmeHelperContext) => void;
}

const TermsOfServicePage: React.FC<TermsOfServicePageProps> = ({ onSetHelperContext }) => {
  return (
    <div className="animate-fade-in container mx-auto px-6 py-16" onMouseEnter={() => onSetHelperContext('APP_TERMS')}>
      <div className="max-w-4xl mx-auto prose dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-sm text-slate-500">Last updated: {new Date().toLocaleDateString()}</p>

        <p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the SMEPro.app website and the SMEPro application (the "Service") operated by SMEPro Technologies ("us", "we", or "our").</p>

        <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>

        <h2>1. Accounts</h2>
        <p>When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
        <p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.</p>
        
        <h2>2. Intellectual Property</h2>
        <p>The Service and its original content, features, and functionality are and will remain the exclusive property of SMEPro Technologies. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of SMEPro Technologies.</p>
        <p>The content you generate using the Service, including chat conversations and Vault items ("User Content"), remains your property. You grant us a limited license to store, process, and display your User Content solely for the purpose of providing the Service to you.</p>

        <h2>3. Acceptable Use</h2>
        <p>You agree not to use the Service for any unlawful purpose or to violate any person's rights. Please refer to our "Acceptable Use & SAFE AI Policy" for detailed guidelines on prohibited activities.</p>

        <h2>4. Subscriptions</h2>
        <p>Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in advance on a recurring and periodic basis ("Billing Cycle"). Billing cycles are set either on a monthly or annual basis, depending on the type of subscription plan you select when purchasing a Subscription.</p>
        <p>All payments are handled by a third-party payment processor (Stripe). You can manage your subscription through the customer portal provided by our payment processor.</p>

        <h2>5. Limitation of Liability</h2>
        <p>In no event shall SMEPro Technologies, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.</p>

        <h2>6. Disclaimer</h2>
        <p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>
        <p>SMEPro Technologies does not warrant that the outputs generated by the AI are accurate, reliable, or correct; that the Service will meet your requirements; that the Service will be available at any particular time or location, uninterrupted or secure; or that any defects or errors will be corrected.</p>

        <h2>7. Governing Law</h2>
        <p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which SMEPro Technologies is established, without regard to its conflict of law provisions.</p>
        
        <h2>8. Changes</h2>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

        <h2>9. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us at: <a href="mailto:admin@smepro.app">admin@smepro.app</a></p>

      </div>
    </div>
  );
};

export default TermsOfServicePage;